// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnKDfFYa66iaio92x9m2fuIo6AZK7FaSY',
    appId: '1:817504572452:web:3bfc2e888f0f1cb3d834b1',
    messagingSenderId: '817504572452',
    projectId: 'ddcet-36b36',
    authDomain: 'ddcet-36b36.firebaseapp.com',
    storageBucket: 'ddcet-36b36.firebasestorage.app',
    measurementId: 'G-BPE49X1YCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIgADPeNEiCd_wwTMq4TSaPuyG4nyzb04',
    appId: '1:817504572452:android:32f6b41fea55ca5ad834b1',
    messagingSenderId: '817504572452',
    projectId: 'ddcet-36b36',
    storageBucket: 'ddcet-36b36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1x0okMSLowEqwY48FADpNNXDbsQ9SWeg',
    appId: '1:817504572452:ios:723910f9f7a5c820d834b1',
    messagingSenderId: '817504572452',
    projectId: 'ddcet-36b36',
    storageBucket: 'ddcet-36b36.firebasestorage.app',
    iosBundleId: 'com.example.ddcetPreparation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1x0okMSLowEqwY48FADpNNXDbsQ9SWeg',
    appId: '1:817504572452:ios:723910f9f7a5c820d834b1',
    messagingSenderId: '817504572452',
    projectId: 'ddcet-36b36',
    storageBucket: 'ddcet-36b36.firebasestorage.app',
    iosBundleId: 'com.example.ddcetPreparation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnKDfFYa66iaio92x9m2fuIo6AZK7FaSY',
    appId: '1:817504572452:web:80d364c58c3e72ddd834b1',
    messagingSenderId: '817504572452',
    projectId: 'ddcet-36b36',
    authDomain: 'ddcet-36b36.firebaseapp.com',
    storageBucket: 'ddcet-36b36.firebasestorage.app',
    measurementId: 'G-JFL6VQHKPD',
  );
}
